//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public string Id { get; set; }
        public string InvoiceNo { get; set; }
        public string SaleId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<double> OutstandingInvoiceAmount { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual tblSale tblSale { get; set; }
    }
}
