//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public string Id { get; set; }
        public string CategoryId { get; set; }
        public string Unitid { get; set; }
        public string SupplierId { get; set; }
        public string ShipperId { get; set; }
        public string ProductNo { get; set; }
        public string ProductCode { get; set; }
        public string ProductImage { get; set; }
        public Nullable<double> QuantityInStock { get; set; }
        public Nullable<double> PriceInStock { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> QuantityInStockRetail { get; set; }
        public Nullable<double> quantity_alert { get; set; }
    }
}
