//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseBySupplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseBySupplier()
        {
            this.tblPurchaseBySupplierDetails = new HashSet<tblPurchaseBySupplierDetail>();
        }
    
        public string Id { get; set; }
        public string SupplierId { get; set; }
        public string ShipperId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> ShipperAmount { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string PurchaseStatus { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPurchaseBySupplierDetail> tblPurchaseBySupplierDetails { get; set; }
    }
}
