//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseBySupplierDetail
    {
        public string Id { get; set; }
        public string PurchaseBySupplierId { get; set; }
        public string ProductId { get; set; }
        public string UnitTypeId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    
        public virtual tblPurchaseBySupplier tblPurchaseBySupplier { get; set; }
    }
}
