//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSale()
        {
            this.tblInvoices = new HashSet<tblInvoice>();
            this.tblSalesDetails = new HashSet<tblSalesDetail>();
            this.tbSalePayments = new HashSet<tbSalePayment>();
        }
    
        public string Id { get; set; }
        public string CustomerId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string SaleCode { get; set; }
        public Nullable<double> Owe { get; set; }
        public string InvoiceStatus { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> RevicedFromCustomer { get; set; }
        public Nullable<int> customer_location { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<decimal> ReceivedByABA { get; set; }
        public Nullable<decimal> SaleAmount { get; set; }
        public Nullable<decimal> SaleDeposit { get; set; }
        public Nullable<decimal> SaleCost { get; set; }
        public Nullable<decimal> Profit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesDetail> tblSalesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbSalePayment> tbSalePayments { get; set; }
    }
}
