//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jotun.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSalePayment
    {
        public string sale_payment_id { get; set; }
        public string sale_id { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public Nullable<decimal> owe_amount { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<decimal> payment_amount_aba { get; set; }
    
        public virtual tblSale tblSale { get; set; }
    }
}
